<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Explorer.aspx.cs" Inherits="MiniTorrent.WebPortal.Explorer" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <!-- #include file ="_Layout.html" -->

    <form id="form1" runat="server">
        <div class="container">

            <h2>File List Available </h2>
            <h3><asp:Label ID="Label1" runat="server" Text="Search by name"></asp:Label></h3>
            <div class="row p-3">

                <asp:TextBox ID ="txtSearch" runat="server" AutoPostBack="True" OnTextChanged="txtSearch_TextChanged"></asp:TextBox>
                <asp:Button CssClass="btn btn-primary"  ID="btnSearch" OnClick="btnSearch_Click" runat="server" Text="Search Now" />
                <asp:Button  CssClass="btn btn-warning" ID="btnClear" OnClick="btnClear_Click" runat="server" Text="Clear" />

            
            <asp:GridView ID="GridView1" CssClass="table table-hover table-striped" runat="server" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                    <asp:BoundField DataField="size" HeaderText="size" SortExpression="size" />
                    <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                    <asp:BoundField DataField="IdUser" HeaderText="IdUser" SortExpression="IdUser" />
                </Columns>
            </asp:GridView>

            </div>

            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MiniTorrentContext %>" SelectCommand="SELECT        MyFiles.Id, MyFiles.name, MyFiles.size, MyFiles.description, MyFiles.IdUser
FROM            MyFiles INNER JOIN
                         Users ON MyFiles.IdUser = Users.Id
WHERE        (Users.active = 'true')"
                FilterExpression="name LIKE '%{0}%'">
                <FilterParameters>
                    <asp:ControlParameter Name="name" ControlID="txtSearch" PropertyName="Text" />
                </FilterParameters>
            </asp:SqlDataSource>

            <h2>Active Users</h2>
            <asp:GridView ID="GridView2" UseAccessibleHeader="true" CssClass="table table-hover table-striped" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="ActiveUsersSqlDataSource2">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                    <asp:BoundField DataField="password" HeaderText="password" SortExpression="password" />
                    <asp:BoundField DataField="IP" HeaderText="IP" SortExpression="IP" />
                    <asp:BoundField DataField="port" HeaderText="port" SortExpression="port" />
                    <asp:BoundField DataField="PublicPath" HeaderText="PublicPath" SortExpression="PublicPath" />
                    <asp:BoundField DataField="DownloadPath" HeaderText="DownloadPath" SortExpression="DownloadPath" />
                    <asp:CheckBoxField DataField="active" HeaderText="active" SortExpression="active" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="ActiveUsersSqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:MiniTorrentContext %>" SelectCommand="SELECT * FROM [Users] WHERE active = 'true'"></asp:SqlDataSource>


            <hr />

            <h2>Total Users</h2>

            <asp:GridView ID="GridView4" CssClass="table table-hover table-striped" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="TotalUserSqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                    <asp:BoundField DataField="password" HeaderText="password" SortExpression="password" />
                    <asp:BoundField DataField="IP" HeaderText="IP" SortExpression="IP" />
                    <asp:BoundField DataField="port" HeaderText="port" SortExpression="port" />
                    <asp:BoundField DataField="PublicPath" HeaderText="PublicPath" SortExpression="PublicPath" />
                    <asp:BoundField DataField="DownloadPath" HeaderText="DownloadPath" SortExpression="DownloadPath" />
                    <asp:CheckBoxField DataField="active" HeaderText="active" SortExpression="active" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="TotalUserSqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:MiniTorrentContext %>" SelectCommand="SELECT * FROM [Users]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [Users] WHERE [Id] = @original_Id AND (([username] = @original_username) OR ([username] IS NULL AND @original_username IS NULL)) AND (([password] = @original_password) OR ([password] IS NULL AND @original_password IS NULL)) AND (([IP] = @original_IP) OR ([IP] IS NULL AND @original_IP IS NULL)) AND [port] = @original_port AND (([PublicPath] = @original_PublicPath) OR ([PublicPath] IS NULL AND @original_PublicPath IS NULL)) AND (([DownloadPath] = @original_DownloadPath) OR ([DownloadPath] IS NULL AND @original_DownloadPath IS NULL)) AND [active] = @original_active;

DELETE FROM [MyFiles] WHERE [IdUser] = @original_Id"
                InsertCommand="INSERT INTO [Users] ([username], [password], [IP], [port], [PublicPath], [DownloadPath], [active]) VALUES (@username, @password, @IP, @port, @PublicPath, @DownloadPath, @active)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [Users] SET [username] = @username, [password] = @password, [IP] = @IP, [port] = @port, [PublicPath] = @PublicPath, [DownloadPath] = @DownloadPath, [active] = @active WHERE [Id] = @original_Id AND (([username] = @original_username) OR ([username] IS NULL AND @original_username IS NULL)) AND (([password] = @original_password) OR ([password] IS NULL AND @original_password IS NULL)) AND (([IP] = @original_IP) OR ([IP] IS NULL AND @original_IP IS NULL)) AND [port] = @original_port AND (([PublicPath] = @original_PublicPath) OR ([PublicPath] IS NULL AND @original_PublicPath IS NULL)) AND (([DownloadPath] = @original_DownloadPath) OR ([DownloadPath] IS NULL AND @original_DownloadPath IS NULL)) AND [active] = @original_active">
                <DeleteParameters>
                    <asp:Parameter Name="original_Id" Type="Int32" />
                    <asp:Parameter Name="original_username" Type="String" />
                    <asp:Parameter Name="original_password" Type="String" />
                    <asp:Parameter Name="original_IP" Type="String" />
                    <asp:Parameter Name="original_port" Type="Int32" />
                    <asp:Parameter Name="original_PublicPath" Type="String" />
                    <asp:Parameter Name="original_DownloadPath" Type="String" />
                    <asp:Parameter Name="original_active" Type="Boolean" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="username" Type="String" />
                    <asp:Parameter Name="password" Type="String" />
                    <asp:Parameter Name="IP" Type="String" />
                    <asp:Parameter Name="port" Type="Int32" />
                    <asp:Parameter Name="PublicPath" Type="String" />
                    <asp:Parameter Name="DownloadPath" Type="String" />
                    <asp:Parameter Name="active" Type="Boolean" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="username" Type="String" />
                    <asp:Parameter Name="password" Type="String" />
                    <asp:Parameter Name="IP" Type="String" />
                    <asp:Parameter Name="port" Type="Int32" />
                    <asp:Parameter Name="PublicPath" Type="String" />
                    <asp:Parameter Name="DownloadPath" Type="String" />
                    <asp:Parameter Name="active" Type="Boolean" />
                    <asp:Parameter Name="original_Id" Type="Int32" />
                    <asp:Parameter Name="original_username" Type="String" />
                    <asp:Parameter Name="original_password" Type="String" />
                    <asp:Parameter Name="original_IP" Type="String" />
                    <asp:Parameter Name="original_port" Type="Int32" />
                    <asp:Parameter Name="original_PublicPath" Type="String" />
                    <asp:Parameter Name="original_DownloadPath" Type="String" />
                    <asp:Parameter Name="original_active" Type="Boolean" />
                </UpdateParameters>
            </asp:SqlDataSource>


            <h2>Total Files </h2>



            <asp:GridView ID="GridView5" UseAccessibleHeader="true" CssClass="table table-hover table-striped" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="TotalFilesSqlDataSource2">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                    <asp:BoundField DataField="size" HeaderText="size" SortExpression="size" />
                    <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                    <asp:BoundField DataField="IdUser" HeaderText="IdUser" SortExpression="IdUser" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="TotalFilesSqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:MiniTorrentContext %>" SelectCommand="SELECT * FROM [MyFiles]"></asp:SqlDataSource>

        </div>
    </form>
</body>
</html>
